# Generated by Django 5.1.6 on 2025-02-17 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_withdraw_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200, null=True)),
                ('message', models.CharField(max_length=200, null=True)),
                ('customer_reference', models.CharField(max_length=200, null=True)),
                ('internal_reference', models.CharField(max_length=200, null=True)),
                ('msisdn', models.CharField(max_length=200, null=True)),
                ('amount', models.FloatField(default=0)),
                ('currency', models.CharField(max_length=200, null=True)),
                ('provider', models.CharField(max_length=200, null=True)),
                ('charge', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='investmentperformance',
            old_name='performance_value',
            new_name='management_fee',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='networth',
        ),
        migrations.RemoveField(
            model_name='networth',
            name='goal',
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_picture',
            field=models.ImageField(default='default_picture.jpg', upload_to='goal'),
        ),
        migrations.AddField(
            model_name='investmentclass',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='investmentclass',
            name='logo',
            field=models.ImageField(default='default_picture.jpg', upload_to='investmentClasses'),
        ),
        migrations.AddField(
            model_name='investmentperformance',
            name='performance_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='networth',
            name='deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.deposit'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='passcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='reference_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='txRef',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='networth',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InvestmentTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdraw_amount', models.FloatField(default=0)),
                ('deposit_amount', models.FloatField(default=0)),
                ('opening_balance', models.FloatField(default=0)),
                ('interest', models.FloatField(default=0)),
                ('management_fee', models.FloatField(default=0)),
                ('performance_fee', models.FloatField(default=0)),
                ('closing_balance', models.FloatField(default=0)),
                ('risk_profile', models.BooleanField(default=False)),
                ('out_performance', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('investment_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.investmentoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
